[tool.poetry]
name = "seo_friendly_urls_django"
version = "0.0.1"
description = ""
authors = ["Dani Hodovic"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
django = "^2.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
